// LanguageContext.jsx
import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
    en: {
        // --- General & App ---
        "app.title": "Mentorship Dashboard",
        "tab.skills": "Skills Observation (Provider)",
        "tab.mothers": "Mother Interviews",
        "tab.visit_reports": "Visit Reports (Facility)",
        "tab.admin": "Admin Dashboard",
        "btn.refresh": "Refresh",
        "btn.back": "Back to Main Menu",
        
        // --- Filters ---
        "filter.date": "Date Filter",
        "filter.state": "State",
        "filter.locality": "Locality",
        "filter.facility": "Health Facility",
        "filter.project": "Project / Partner",
        "filter.job_title": "Job Title",
        "filter.worker_name": "Health Worker Name",
        
        "filter.all.time": "All Time",
        "filter.all.states": "All States",
        "filter.all.localities": "All Localities",
        "filter.all.facilities": "All Facilities",
        "filter.all.projects": "All Projects",
        "filter.all.titles": "All Titles",
        "filter.all.workers": "All Workers",
        
        // --- Dates ---
        "date.today": "Today",
        "date.yesterday": "Yesterday",
        "date.this_week": "This Week",
        "date.last_week": "Last Week",
        "date.this_month": "This Month",
        "date.last_month": "Last Month",
        "date.this_year": "This Year",
        "date.last_year": "Last Year",

        // --- Messages ---
        "msg.loading": "Loading Dashboard Data...",
        "msg.please_wait": "Please wait while we fetch the latest records.",
        "msg.filtered_by": "Filtered by",
        "msg.all_sudan": "All Sudan Data",
        
        // --- Shared Tables & KPIs ---
        "Copy as Image": "Copy as Image",
        "Value": "Value",
        "Count": "Count",
        "Percentage": "Percentage",
        "Skill": "Skill",
        "Skill (EENC)": "Skill (EENC)",
        "Count (Yes / Total)": "Count (Yes / Total)",
        "Count (Yes / Partial / No)": "Count (Yes / Partial / No)",
        "Question (Mother Survey)": "Question (Mother Survey)",
        "KPI Name": "KPI Name",
        "Overall Score": "Overall Score",
        "Total Completed Visits": "Total Completed Visits",
        "Visits per HW": "Visits per HW",
        "Total HWs Visited": "Total HWs Visited",
        "Total Cases Observed": "Total Cases Observed",
        "Cases per Visit": "Cases per Visit",
        "Mentor Name": "Mentor Name",
        "Health Workers": "Health Workers",
        "Mother Forms": "Mother Forms",
        "Forms per Visit": "Forms per Visit",
        "Visit Reports": "Visit Reports",
        "% of Completed Visits": "% of Completed Visits",
        "No detailed skill data available.": "No detailed skill data available.",
        "No detailed EENC skill data available.": "No detailed EENC skill data available.",
        "No mother survey data available.": "No mother survey data available.",
        "No data available.": "No data available.",
        "Yes": "Yes",
        "Partial": "Partial",
        "No": "No",
        "submitted": "submitted",
        "visits/hw": "visits/hw",
        "cases/visit": "cases/visit",
        "forms/visit": "forms/visit",

        // --- Provider Skills (IMNCI & EENC) ---
        "Overall Adherence Score": "Overall Adherence Score",
        "Assess & Classify": "Assess & Classify",
        "Final Decision": "Final Decision",
        "Treatment & Counsel": "Treatment & Counsel",
        "Danger Signs Assessment": "Danger Signs Assessment",
        "Asked/Checked: Cannot Drink/Breastfeed": "Asked/Checked: Cannot Drink/Breastfeed",
        "Asked/Checked: Vomits Everything": "Asked/Checked: Vomits Everything",
        "Asked/Checked: Convulsions": "Asked/Checked: Convulsions",
        "Checked: Lethargic/Unconscious": "Checked: Lethargic/Unconscious",
        "Measurement Skills (Average)": "Measurement Skills (Average)",
        "Weight Measured Correctly": "Weight Measured Correctly",
        "Temp Measured Correctly": "Temp Measured Correctly",
        "Height Measured Correctly": "Height Measured Correctly",
        "Correct Respiratory Rate Measurement": "Correct Respiratory Rate Measurement",
        "Correct Dehydration assessment": "Correct Dehydration assessment",
        "Correct Malnutrition Assessment": "Correct Malnutrition Assessment",
        "MUAC Measured Correctly": "MUAC Measured Correctly",
        "Z-Score (WFH) Measured Correctly": "Z-Score (WFH) Measured Correctly",
        "Percentage of cases assessed for Immunization correctly": "Percentage of cases assessed for Immunization correctly",
        "Percentage of cases assessed for vitamin supplementation correctly": "Percentage of cases assessed for vitamin supplementation correctly",
        "Percentage of Pneumonia cases Treated correctly with Amoxicillin": "Percentage of Pneumonia cases Treated correctly with Amoxicillin",
        "Percentage of Diarrhea cases Treated with ORS": "Percentage of Diarrhea cases Treated with ORS",
        "Percentage of Diarrhea cases Treated with Zinc": "Percentage of Diarrhea cases Treated with Zinc",
        "Percentage of malaria cases treated with Coartum": "Percentage of malaria cases treated with Coartum",
        "Percentage of cases advised when to return immediately": "Percentage of cases advised when to return immediately",
        "Percentage of cases advised to return for follow up": "Percentage of cases advised to return for follow up",
        "Recording Form Use": "Recording Form Use",
        "Registering Signs": "Registering Signs",
        "Registering Classifications": "Registering Classifications",
        "Registering Treatments": "Registering Treatments",
        "Did health worker's decision match the supervisor's?": "Did health worker's decision match the supervisor's?",
        "KPI Summary by Job Description": "KPI Summary by Job Description",
        "Overall Adherence by": "Overall Adherence by",
        "Detailed Skill Performance": "Detailed Skill Performance",
        "Overall IMNCI Adherence": "Overall IMNCI Adherence",
        "Core Components Adherence": "Core Components Adherence",
        "Adherence Over Time (Danger Signs)": "Adherence Over Time (Danger Signs)",
        "Adherence Over Time (Measurement Skills)": "Adherence Over Time (Measurement Skills)",
        "Adherence Over Time (Malnutrition Signs)": "Adherence Over Time (Malnutrition Signs)",
        "Recording Form Use Over Time": "Recording Form Use Over Time",
        "Overall IMNCI Adherence by": "Overall IMNCI Adherence by",
        
        "Total Completed EENC Visits": "Total Completed EENC Visits",
        "Overall EENC Adherence Scores (Average)": "Overall EENC Adherence Scores (Average)",
        "Overall EENC Adherence": "Overall EENC Adherence",
        "Preparation Score": "Preparation Score",
        "Drying & Stimulation Score": "Drying & Stimulation Score",
        "Breathing Baby Mgmt Score": "Breathing Baby Mgmt Score",
        "Resuscitation Score": "Resuscitation Score",
        "EENC Adherence Over Time (Main KPIs)": "EENC Adherence Over Time (Main KPIs)",
        "KPI 1: Infection Control (All Cases)": "KPI 1: Infection Control (All Cases)",
        "Hand Washing (1st)": "Hand Washing (1st)",
        "Hand Washing (2nd)": "Hand Washing (2nd)",
        "Sterile Gloves Used": "Sterile Gloves Used",
        "KPI 1 Over Time: Infection Control": "KPI 1 Over Time: Infection Control",
        "KPI 2: Resuscitation Preparedness (All Cases)": "KPI 2: Resuscitation Preparedness (All Cases)",
        "Towels Prepared": "Towels Prepared",
        "Resus Equipment Ready": "Resus Equipment Ready",
        "Ambu Bag Checked": "Ambu Bag Checked",
        "KPI 2 Over Time: Preparedness": "KPI 2 Over Time: Preparedness",
        "KPI 3: Early Care (All Cases)": "KPI 3: Early Care (All Cases)",
        "Drying within 5 sec": "Drying within 5 sec",
        "Immediate Skin-to-Skin": "Immediate Skin-to-Skin",
        "Dry Towel & Hat Used": "Dry Towel & Hat Used",
        "KPI 3 Over Time: Early Care": "KPI 3 Over Time: Early Care",
        "KPI 4: Cord Management (Breathing Babies)": "KPI 4: Cord Management (Breathing Babies)",
        "Hygienic Cord Check": "Hygienic Cord Check",
        "Delayed Clamping": "Delayed Clamping",
        "Correct Clamping": "Correct Clamping",
        "KPI 4 Over Time: Cord Mgmt": "KPI 4 Over Time: Cord Mgmt",
        "KPI 5: Breastfeeding (Breathing Babies)": "KPI 5: Breastfeeding (Breathing Babies)",
        "Early Breastfeeding Advice": "Early Breastfeeding Advice",
        "KPI 5 Over Time: Breastfeeding": "KPI 5 Over Time: Breastfeeding",
        "KPI 6: Resuscitation Execution (Non-Breathing)": "KPI 6: Resuscitation Execution (Non-Breathing)",
        "Head Positioning": "Head Positioning",
        "Good Mask Seal": "Good Mask Seal",
        "Chest Rise (1st min)": "Chest Rise (1st min)",
        "Adequate Rate (30-50)": "Adequate Rate (30-50)",
        "KPI 6 Over Time: Resuscitation": "KPI 6 Over Time: Resuscitation",
        "Overall EENC Adherence by": "Overall EENC Adherence by",
        "Detailed EENC Skill Performance": "Detailed EENC Skill Performance",

        // --- Mother Interviews ---
        "Total Mother Interviews": "Total Mother Interviews",
        "Mother Knowledge: Treatment": "Mother Knowledge: Treatment",
        "Knows Med Details": "Knows Med Details",
        "Knows Treatment Details": "Knows Treatment Details",
        "Knows Return Date": "Knows Return Date",
        "Knowledge (Meds) Over Time": "Knowledge (Meds) Over Time",
        "Mother Knowledge: ORS & Fluids": "Mother Knowledge: ORS & Fluids",
        "Knows ORS Prep": "Knows ORS Prep",
        "Knows Home Fluids": "Knows Home Fluids",
        "Knows 4 Rules": "Knows 4 Rules",
        "Knowledge (ORS) Over Time": "Knowledge (ORS) Over Time",
        "Mother Satisfaction": "Mother Satisfaction",
        "Satisfaction: Time Spent": "Satisfaction: Time Spent",
        "Satisfaction: Communication": "Satisfaction: Communication",
        "Satisfaction: Learned Something": "Satisfaction: Learned Something",
        "Satisfaction Over Time": "Satisfaction Over Time",
        "Overall Mother Interview Scores by": "Overall Mother Interview Scores by",
        "Average Mother Knowledge/Satisfaction by": "Average Mother Knowledge/Satisfaction by",
        "Detailed Mother Interview Performance": "Detailed Mother Interview Performance",
        "Mother Interview: Skin-to-Skin Care": "Mother Interview: Skin-to-Skin Care",
        "Uninterrupted 90min S2S": "Uninterrupted 90min S2S",
        "Skin-to-Skin Over Time": "Skin-to-Skin Over Time",
        "Mother Interview: Breastfeeding": "Mother Interview: Breastfeeding",
        "Feeding in 1st Hour": "Feeding in 1st Hour",
        "Given Substitutes (Yes)": "Given Substitutes (Yes)",
        "Feeding with Bottle (Yes)": "Feeding with Bottle (Yes)",
        "Breastfeeding Over Time": "Breastfeeding Over Time",
        "Mother Interview: Skin & Cord Care": "Mother Interview: Skin & Cord Care",
        "Vitamin K Given": "Vitamin K Given",
        "Eye Ointment Given": "Eye Ointment Given",
        "Cord Substance Applied": "Cord Substance Applied",
        "Care Indicators Over Time": "Care Indicators Over Time",
        "Mother Interview: Oiling & Bathing": "Mother Interview: Oiling & Bathing",
        "Skin Oiling (Yes)": "Skin Oiling (Yes)",
        "Bathing < 6hrs (Yes)": "Bathing < 6hrs (Yes)",
        "Hygiene Indicators Over Time": "Hygiene Indicators Over Time",
        "Mother Interview: Vaccination": "Mother Interview: Vaccination",
        "Polio Vaccine (Zero)": "Polio Vaccine (Zero)",
        "BCG Vaccine": "BCG Vaccine",
        "Vaccination Over Time": "Vaccination Over Time",
        "Mother Interview: Measurements": "Mother Interview: Measurements",
        "Weight Measured": "Weight Measured",
        "Temp Measured": "Temp Measured",
        "Measurements Over Time": "Measurements Over Time",
        "Mother Interview: Registration": "Mother Interview: Registration",
        "Civil Registration": "Civil Registration",
        "Discharge Card Given": "Discharge Card Given",
        "Registration Over Time": "Registration Over Time",
        "Overall Mother Interview Indicators by": "Overall Mother Interview Indicators by",
        "Average Indicator Presence by": "Average Indicator Presence by",

        // --- Visit Reports ---
        "Total Visit Reports": "Total Visit Reports",
        "Total Number of Training Sessions": "Total Number of Training Sessions",
        "mean sessions per visit": "mean sessions per visit",
        "Note: To view Information System and Drug Shortage data, ensure rawReports is included.": "Note: To view Information System and Drug Shortage data, ensure rawReports is included.",
        "Information System KPIs (Overall)": "Information System KPIs (Overall)",
        "Children seen by IMNCI trained cadre": "Children seen by IMNCI trained cadre",
        "Children with IMNCI recording form": "Children with IMNCI recording form",
        "Children returning for follow up": "Children returning for follow up",
        "total": "total",
        "trained": "trained",
        "Visit": "Visit",
        "Seen by Trained Cadre (%)": "Seen by Trained Cadre (%)",
        "With Recording Form (%)": "With Recording Form (%)",
        "Return for Follow-up (%)": "Return for Follow-up (%)",
        "Information System Performance Over Time": "Information System Performance Over Time",
        "KPI Performance (%)": "KPI Performance (%)",
        "Facility Drug Availability (Percentage of facilities reporting drugs always available)": "Facility Drug Availability (Percentage of facilities reporting drugs always available)",
        "Amoxicillin": "Amoxicillin",
        "Zinc": "Zinc",
        "ORS": "ORS",
        "Coartem": "Coartem",
        "Availability": "Availability",
        "of": "of",
        "facilities": "facilities",
        "Drug Availability Over Time": "Drug Availability Over Time",
        "Facilities with Drug Available (%)": "Facilities with Drug Available (%)",
        "Times Trained": "Times Trained",
        "% of Total Training Sessions": "% of Total Training Sessions",
        "No training data recorded.": "No training data recorded.",
        "Visit Breakdown & Skills Trained by Facility": "Visit Breakdown & Skills Trained by Facility",
        "Facility": "Facility",
        "No visits found for current filter.": "No visits found for current filter.",
        "Total Visits by": "Total Visits by",
        "Facility Problems & Solutions (Combined)": "Facility Problems & Solutions (Combined)",
        "Problem / Challenge": "Problem / Challenge",
        "Implemented Solution": "Implemented Solution",
        "Status": "Status",
        "Responsible Person": "Responsible Person",
        "No problems recorded.": "No problems recorded."
    },
    ar: {
        // --- General & App ---
        "app.title": "لوحة متابعة الإشراف",
        "tab.skills": "مراقبة المهارات (مقدم الخدمة)",
        "tab.mothers": "مقابلات الأمهات",
        "tab.visit_reports": "تقارير الزيارات (المؤسسة)",
        "tab.admin": "لوحة تحكم المشرف",
        "btn.refresh": "تحديث",
        "btn.back": "العودة للقائمة الرئيسية",
        
        // --- Filters ---
        "filter.date": "تصفية حسب التاريخ",
        "filter.state": "الولاية",
        "filter.locality": "المحلية",
        "filter.facility": "المؤسسة الصحية",
        "filter.project": "المشروع / الشريك",
        "filter.job_title": "الوصف الوظيفي",
        "filter.worker_name": "اسم العامل الصحي",
        
        "filter.all.time": "كل الأوقات",
        "filter.all.states": "كل الولايات",
        "filter.all.localities": "كل المحليات",
        "filter.all.facilities": "كل المؤسسات",
        "filter.all.projects": "كل المشاريع",
        "filter.all.titles": "كل الوظائف",
        "filter.all.workers": "كل الكوادر",
        
        // --- Dates ---
        "date.today": "اليوم",
        "date.yesterday": "الأمس",
        "date.this_week": "هذا الأسبوع",
        "date.last_week": "الأسبوع الماضي",
        "date.this_month": "هذا الشهر",
        "date.last_month": "الشهر الماضي",
        "date.this_year": "هذا العام",
        "date.last_year": "العام الماضي",

        // --- Messages ---
        "msg.loading": "جاري تحميل بيانات اللوحة...",
        "msg.please_wait": "يرجى الانتظار بينما نقوم بجلب أحدث السجلات.",
        "msg.filtered_by": "تمت التصفية حسب",
        "msg.all_sudan": "بيانات كل السودان",
        
        // --- Shared Tables & KPIs ---
        "Copy as Image": "نسخ كصورة",
        "Value": "القيمة",
        "Count": "العدد",
        "Percentage": "النسبة المئوية",
        "Skill": "المهارة",
        "Skill (EENC)": "المهارة (EENC)",
        "Count (Yes / Total)": "العدد (نعم / المجموع)",
        "Count (Yes / Partial / No)": "العدد (نعم / جزئي / لا)",
        "Question (Mother Survey)": "السؤال (استبيان الأم)",
        "KPI Name": "مؤشر الأداء",
        "Overall Score": "الدرجة الكلية",
        "Total Completed Visits": "إجمالي الزيارات المكتملة",
        "Visits per HW": "زيارات لكل عامل",
        "Total HWs Visited": "إجمالي الكوادر",
        "Total Cases Observed": "إجمالي الحالات المراقبة",
        "Cases per Visit": "حالات لكل زيارة",
        "Mentor Name": "اسم المشرف",
        "Health Workers": "الكوادر الصحية",
        "Mother Forms": "استبيانات الأمهات",
        "Forms per Visit": "استبيان لكل زيارة",
        "Visit Reports": "تقارير الزيارات",
        "% of Completed Visits": "% من الزيارات المكتملة",
        "No detailed skill data available.": "لا توجد بيانات تفصيلية للمهارات.",
        "No detailed EENC skill data available.": "لا توجد بيانات تفصيلية لمهارات EENC.",
        "No mother survey data available.": "لا توجد بيانات لاستبيان الأمهات.",
        "No data available.": "لا توجد بيانات متاحة.",
        "Yes": "نعم",
        "Partial": "جزئي",
        "No": "لا",
        "submitted": "مُقدم",
        "visits/hw": "زيارة/عامل",
        "cases/visit": "حالة/زيارة",
        "forms/visit": "استبيان/زيارة",

        // --- Provider Skills (IMNCI & EENC) ---
        "Overall Adherence Score": "درجة الالتزام الكلية",
        "Assess & Classify": "التقييم والتصنيف",
        "Final Decision": "القرار النهائي",
        "Treatment & Counsel": "العلاج والنصح",
        "Danger Signs Assessment": "تقييم علامات الخطورة",
        "Asked/Checked: Cannot Drink/Breastfeed": "سأل/فحص: لا يستطيع الشرب أو الرضاعة",
        "Asked/Checked: Vomits Everything": "سأل/فحص: يتقيأ كل شيء",
        "Asked/Checked: Convulsions": "سأل/فحص: تشنجات",
        "Checked: Lethargic/Unconscious": "فحص: خمول أو فقدان وعي",
        "Measurement Skills (Average)": "مهارات القياس (متوسط)",
        "Weight Measured Correctly": "تم قياس الوزن بشكل صحيح",
        "Temp Measured Correctly": "تم قياس الحرارة بشكل صحيح",
        "Height Measured Correctly": "تم قياس الطول بشكل صحيح",
        "Correct Respiratory Rate Measurement": "القياس الصحيح لمعدل التنفس",
        "Correct Dehydration assessment": "التقييم الصحيح للجفاف",
        "Correct Malnutrition Assessment": "التقييم الصحيح لسوء التغذية",
        "MUAC Measured Correctly": "تم قياس MUAC بشكل صحيح",
        "Z-Score (WFH) Measured Correctly": "تم قياس Z-Score بشكل صحيح",
        "Percentage of cases assessed for Immunization correctly": "نسبة الحالات التي تم تقييم التطعيم لها بشكل صحيح",
        "Percentage of cases assessed for vitamin supplementation correctly": "نسبة الحالات التي تم تقييم فيتامين أ لها بشكل صحيح",
        "Percentage of Pneumonia cases Treated correctly with Amoxicillin": "نسبة حالات الالتهاب الرئوي المعالجة بالأموكسيسيلين",
        "Percentage of Diarrhea cases Treated with ORS": "نسبة حالات الإسهال المعالجة بأملاح التروية",
        "Percentage of Diarrhea cases Treated with Zinc": "نسبة حالات الإسهال المعالجة بالزنك",
        "Percentage of malaria cases treated with Coartum": "نسبة حالات الملاريا المعالجة بالكورتيم",
        "Percentage of cases advised when to return immediately": "نسبة الحالات التي تم نصحها متى تعود فوراً",
        "Percentage of cases advised to return for follow up": "نسبة الحالات التي تم نصحها بالعودة للمتابعة",
        "Recording Form Use": "استخدام استمارة التسجيل",
        "Registering Signs": "تسجيل العلامات",
        "Registering Classifications": "تسجيل التصنيفات",
        "Registering Treatments": "تسجيل العلاج",
        "Did health worker's decision match the supervisor's?": "هل طابق قرار العامل الصحي قرار المشرف؟",
        "KPI Summary by Job Description": "ملخص مؤشرات الأداء حسب الوصف الوظيفي",
        "Overall Adherence by": "الالتزام الكلي حسب",
        "Detailed Skill Performance": "الأداء التفصيلي للمهارات",
        "Overall IMNCI Adherence": "الالتزام الكلي (IMNCI)",
        "Core Components Adherence": "الالتزام بالمكونات الأساسية",
        "Adherence Over Time (Danger Signs)": "الالتزام بمرور الوقت (علامات الخطورة)",
        "Adherence Over Time (Measurement Skills)": "الالتزام بمرور الوقت (مهارات القياس)",
        "Adherence Over Time (Malnutrition Signs)": "الالتزام بمرور الوقت (علامات سوء التغذية)",
        "Recording Form Use Over Time": "استخدام الاستمارة بمرور الوقت",
        "Overall IMNCI Adherence by": "الالتزام الكلي (IMNCI) حسب",
        
        "Total Completed EENC Visits": "إجمالي زيارات EENC المكتملة",
        "Overall EENC Adherence Scores (Average)": "الالتزام الكلي (EENC) (متوسط)",
        "Overall EENC Adherence": "الالتزام الكلي (EENC)",
        "Preparation Score": "درجة التحضير",
        "Drying & Stimulation Score": "درجة التجفيف والتحفيز",
        "Breathing Baby Mgmt Score": "درجة إدارة الطفل الذي يتنفس",
        "Resuscitation Score": "درجة الإنعاش",
        "EENC Adherence Over Time (Main KPIs)": "الالتزام بمرور الوقت (EENC المكونات الأساسية)",
        "KPI 1: Infection Control (All Cases)": "مؤشر 1: مكافحة العدوى (كل الحالات)",
        "Hand Washing (1st)": "غسل اليدين (الأول)",
        "Hand Washing (2nd)": "غسل اليدين (الثاني)",
        "Sterile Gloves Used": "استخدام قفازات معقمة",
        "KPI 1 Over Time: Infection Control": "مؤشر 1 بمرور الوقت: مكافحة العدوى",
        "KPI 2: Resuscitation Preparedness (All Cases)": "مؤشر 2: جاهزية الإنعاش (كل الحالات)",
        "Towels Prepared": "تجهيز المناشف",
        "Resus Equipment Ready": "تجهيز معدات الإنعاش",
        "Ambu Bag Checked": "فحص حقيبة الإنعاش",
        "KPI 2 Over Time: Preparedness": "مؤشر 2 بمرور الوقت: الجاهزية",
        "KPI 3: Early Care (All Cases)": "مؤشر 3: الرعاية المبكرة (كل الحالات)",
        "Drying within 5 sec": "التجفيف خلال 5 ثواني",
        "Immediate Skin-to-Skin": "تلامس الجلد للجلد فوراً",
        "Dry Towel & Hat Used": "استخدام منشفة جافة وقبعة",
        "KPI 3 Over Time: Early Care": "مؤشر 3 بمرور الوقت: الرعاية المبكرة",
        "KPI 4: Cord Management (Breathing Babies)": "مؤشر 4: العناية بالحبل السري",
        "Hygienic Cord Check": "فحص الحبل السري بنظافة",
        "Delayed Clamping": "تأخير قطع الحبل السري",
        "Correct Clamping": "القطع الصحيح",
        "KPI 4 Over Time: Cord Mgmt": "مؤشر 4 بمرور الوقت: العناية بالحبل السري",
        "KPI 5: Breastfeeding (Breathing Babies)": "مؤشر 5: الرضاعة الطبيعية",
        "Early Breastfeeding Advice": "النصح المبكر بالرضاعة",
        "KPI 5 Over Time: Breastfeeding": "مؤشر 5 بمرور الوقت: الرضاعة",
        "KPI 6: Resuscitation Execution (Non-Breathing)": "مؤشر 6: تنفيذ الإنعاش",
        "Head Positioning": "تعديل وضعية الرأس",
        "Good Mask Seal": "إحكام القناع",
        "Chest Rise (1st min)": "ارتفاع الصدر",
        "Adequate Rate (30-50)": "معدل التنفس (30-50)",
        "KPI 6 Over Time: Resuscitation": "مؤشر 6 بمرور الوقت: الإنعاش",
        "Overall EENC Adherence by": "الالتزام الكلي (EENC) حسب",
        "Detailed EENC Skill Performance": "الأداء التفصيلي لمهارات EENC",

        // --- Mother Interviews ---
        "Total Mother Interviews": "إجمالي مقابلات الأمهات",
        "Mother Knowledge: Treatment": "معرفة الأم: العلاج",
        "Knows Med Details": "تعرف تفاصيل الأدوية",
        "Knows Treatment Details": "تعرف تفاصيل العلاج المزدوج",
        "Knows Return Date": "تعرف تاريخ العودة",
        "Knowledge (Meds) Over Time": "المعرفة (الأدوية) بمرور الوقت",
        "Mother Knowledge: ORS & Fluids": "معرفة الأم: السوائل وأملاح التروية",
        "Knows ORS Prep": "تعرف تحضير أملاح التروية",
        "Knows Home Fluids": "تعرف السوائل المنزلية",
        "Knows 4 Rules": "تعرف القواعد الأربعة",
        "Knowledge (ORS) Over Time": "المعرفة (أملاح التروية) بمرور الوقت",
        "Mother Satisfaction": "رضا الأم",
        "Satisfaction: Time Spent": "الرضا: الوقت المستغرق",
        "Satisfaction: Communication": "الرضا: أسلوب التواصل",
        "Satisfaction: Learned Something": "الرضا: ما تعلمته",
        "Satisfaction Over Time": "الرضا بمرور الوقت",
        "Overall Mother Interview Scores by": "درجات مقابلة الأم حسب",
        "Average Mother Knowledge/Satisfaction by": "متوسط معرفة/رضا الأم حسب",
        "Detailed Mother Interview Performance": "الأداء التفصيلي لمقابلة الأم",
        "Mother Interview: Skin-to-Skin Care": "مقابلة الأم: تلامس الجلد للجلد",
        "Uninterrupted 90min S2S": "تلامس للجلد 90 دقيقة دون انقطاع",
        "Skin-to-Skin Over Time": "تلامس الجلد للجلد بمرور الوقت",
        "Mother Interview: Breastfeeding": "مقابلة الأم: الرضاعة الطبيعية",
        "Feeding in 1st Hour": "الرضاعة في الساعة الأولى",
        "Given Substitutes (Yes)": "إعطاء بدائل الحليب (نعم)",
        "Feeding with Bottle (Yes)": "الرضاعة بالزجاجة (نعم)",
        "Breastfeeding Over Time": "الرضاعة الطبيعية بمرور الوقت",
        "Mother Interview: Skin & Cord Care": "مقابلة الأم: العناية بالجلد والحبل السري",
        "Vitamin K Given": "تم إعطاء فيتامين ك",
        "Eye Ointment Given": "تم إعطاء مرهم العين",
        "Cord Substance Applied": "تم وضع مادة على الحبل السري",
        "Care Indicators Over Time": "مؤشرات العناية بمرور الوقت",
        "Mother Interview: Oiling & Bathing": "مقابلة الأم: التزييت والتحميم",
        "Skin Oiling (Yes)": "تزييت الجلد (نعم)",
        "Bathing < 6hrs (Yes)": "تحميم قبل 6 ساعات (نعم)",
        "Hygiene Indicators Over Time": "مؤشرات النظافة بمرور الوقت",
        "Mother Interview: Vaccination": "مقابلة الأم: التطعيم",
        "Polio Vaccine (Zero)": "لقاح شلل الأطفال (الجرعة الصفرية)",
        "BCG Vaccine": "لقاح السل (BCG)",
        "Vaccination Over Time": "التطعيم بمرور الوقت",
        "Mother Interview: Measurements": "مقابلة الأم: القياسات",
        "Weight Measured": "تم قياس الوزن",
        "Temp Measured": "تم قياس الحرارة",
        "Measurements Over Time": "القياسات بمرور الوقت",
        "Mother Interview: Registration": "مقابلة الأم: التسجيل",
        "Civil Registration": "التسجيل المدني",
        "Discharge Card Given": "تم تسليم كرت الخروج",
        "Registration Over Time": "التسجيل بمرور الوقت",
        "Overall Mother Interview Indicators by": "مؤشرات مقابلة الأم حسب",
        "Average Indicator Presence by": "متوسط توفر المؤشرات حسب",

        // --- Visit Reports ---
        "Total Visit Reports": "إجمالي تقارير الزيارات",
        "Total Number of Training Sessions": "إجمالي عدد جلسات التدريب",
        "mean sessions per visit": "متوسط الجلسات لكل زيارة",
        "Note: To view Information System and Drug Shortage data, ensure rawReports is included.": "ملاحظة: لعرض إحصائيات نظام المعلومات وانقطاع الأدوية، يرجى التأكد من توفر البيانات الأولية (rawReports).",
        "Information System KPIs (Overall)": "مؤشرات نظام المعلومات (الكلية)",
        "Children seen by IMNCI trained cadre": "أطفال فُحصوا بواسطة كادر مدرب",
        "Children with IMNCI recording form": "أطفال لديهم استمارة تسجيل",
        "Children returning for follow up": "أطفال عادوا للمتابعة",
        "total": "المجموع",
        "trained": "مدرب",
        "Visit": "زيارة",
        "Seen by Trained Cadre (%)": "فُحص بكادر مدرب (%)",
        "With Recording Form (%)": "باستمارة تسجيل (%)",
        "Return for Follow-up (%)": "عاد للمتابعة (%)",
        "Information System Performance Over Time": "أداء نظام المعلومات بمرور الوقت",
        "KPI Performance (%)": "أداء المؤشر (%)",
        "Facility Drug Availability (Percentage of facilities reporting drugs always available)": "توفر الأدوية بالمؤسسة (نسبة المؤسسات التي تبلغ عن توفر الأدوية دائماً)",
        "Amoxicillin": "أموكسيسيلين",
        "Zinc": "زنك",
        "ORS": "أملاح التروية",
        "Coartem": "كورتيم",
        "Availability": "توفر",
        "of": "من",
        "facilities": "مؤسسات",
        "Drug Availability Over Time": "توفر الأدوية بمرور الوقت",
        "Facilities with Drug Available (%)": "مؤسسات يتوفر بها الدواء (%)",
        "Times Trained": "مرات التدريب",
        "% of Total Training Sessions": "% من إجمالي الجلسات",
        "No training data recorded.": "لا توجد بيانات تدريب مسجلة.",
        "Visit Breakdown & Skills Trained by Facility": "تفصيل الزيارات والمهارات المدربة حسب المؤسسة",
        "Facility": "المؤسسة",
        "No visits found for current filter.": "لا توجد زيارات للتصفية الحالية.",
        "Total Visits by": "إجمالي الزيارات حسب",
        "Facility Problems & Solutions (Combined)": "مشاكل المؤسسات والحلول",
        "Problem / Challenge": "المشكلة / التحدي",
        "Implemented Solution": "الحل المتبع",
        "Status": "الحالة",
        "Responsible Person": "المسؤول",
        "No problems recorded.": "لا توجد مشاكل مسجلة."
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    const t = (key) => {
        return translations[language]?.[key] || key; 
    };

    const toggleLanguage = () => {
        setLanguage((prevLang) => (prevLang === 'en' ? 'ar' : 'en'));
    };

    useEffect(() => {
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => useContext(LanguageContext);