// LanguageContext.jsx
import React, { createContext, useState, useContext } from 'react';

const translations = {
    en: {
        // --- General & App ---
        "app.title": "Mentorship Dashboard",
        "tab.skills": "Skills Observation (Provider)",
        "tab.mothers": "Mother Interviews",
        "tab.visit_reports": "Visit Reports (Facility)",
        "tab.admin": "Admin Dashboard",
        "btn.refresh": "Refresh",
        "btn.back": "Back to Main Menu",
        
        // --- Filters ---
        "filter.date": "Date Filter",
        "filter.state": "State",
        "filter.locality": "Locality",
        "filter.facility": "Health Facility",
        "filter.project": "Project / Partner",
        "filter.job_title": "Job Title",
        "filter.worker_name": "Health Worker Name",
        
        "filter.all.time": "All Time",
        "filter.all.states": "All States",
        "filter.all.localities": "All Localities",
        "filter.all.facilities": "All Facilities",
        "filter.all.projects": "All Projects",
        "filter.all.titles": "All Titles",
        "filter.all.workers": "All Workers",
        
        // --- Dates ---
        "date.today": "Today",
        "date.yesterday": "Yesterday",
        "date.this_week": "This Week",
        "date.last_week": "Last Week",
        "date.this_month": "This Month",
        "date.last_month": "Last Month",
        "date.this_year": "This Year",
        "date.last_year": "Last Year",

        // --- Messages ---
        "msg.loading": "Loading Dashboard Data...",
        "msg.please_wait": "Please wait while we fetch the latest records.",
        "msg.filtered_by": "Filtered by",
        "msg.all_sudan": "All Sudan Data",
        
        // --- Shared Tables & KPIs ---
        "Copy as Image": "Copy as Image",
        "Value": "Value",
        "Count": "Count",
        "Percentage": "Percentage",
        "Skill": "Skill",
        "Skill (EENC)": "Skill (EENC)",
        "Count (Yes / Total)": "Count (Yes / Total)",
        "Count (Yes / Partial / No)": "Count (Yes / Partial / No)",
        "Question (Mother Survey)": "Question (Mother Survey)",
        "KPI Name": "KPI Name",
        "Overall Score": "Overall Score",
        "Total Completed Visits": "Total Completed Visits",
        "Visits per HW": "Visits per HW",
        "Total HWs Visited": "Total HWs Visited",
        "Total Cases Observed": "Total Cases Observed",
        "Cases per Visit": "Cases per Visit",
        "Mentor Name": "Mentor Name",
        "Health Workers": "Health Workers",
        "Mother Forms": "Mother Forms",
        "Forms per Visit": "Forms per Visit",
        "Visit Reports": "Visit Reports",
        "% of Completed Visits": "% of Completed Visits",
        "No detailed skill data available.": "No detailed skill data available.",
        "No detailed EENC skill data available.": "No detailed EENC skill data available.",
        "No mother survey data available.": "No mother survey data available.",
        "No data available.": "No data available.",
        "Yes": "Yes",
        "Partial": "Partial",
        "No": "No",
        "submitted": "submitted",
        "visits/hw": "visits/hw",
        "cases/visit": "cases/visit",
        "forms/visit": "forms/visit",

        // --- Job Titles ---
        "Medical Officer": "Medical Officer",
        "Medical Assistant": "Medical Assistant",
        "Nurse": "Nurse",
        "Midwife": "Midwife",
        "Unknown Title": "Unknown Title",

        // --- Visit Numbers ---
        "Visit 1": "Visit 1",
        "Visit 2": "Visit 2",
        "Visit 3": "Visit 3",
        "Visit 4": "Visit 4",
        "Visit 5": "Visit 5",
        "Visit 6": "Visit 6",

        // --- Dashboard Labels ---
        "State": "State",
        "Locality": "Locality",
        "Facility & Date": "Facility & Date",
        "Integrated Management of Newborn and Childhood Illnesses (IMNCI)": "Integrated Management of Newborn and Childhood Illnesses (IMNCI)",
        "Early Essential Newborn Care (EENC)": "Early Essential Newborn Care (EENC)",
        "Infection Control": "Infection Control",
        "Cord Management (Breathing Babies)": "Cord Management (Breathing Babies)",

        // --- Provider Skills (IMNCI & EENC) ---
        "Overall Adherence Score": "Overall Adherence Score",
        "Assess & Classify": "Assess & Classify",
        "Final Decision": "Final Decision",
        "Treatment & Counsel": "Treatment & Counsel",
        "Danger Signs Assessment": "Danger Signs Assessment",
        "Asked/Checked: Cannot Drink/Breastfeed": "Asked/Checked: Cannot Drink/Breastfeed",
        "Asked/Checked: Vomits Everything": "Asked/Checked: Vomits Everything",
        "Asked/Checked: Convulsions": "Asked/Checked: Convulsions",
        "Checked: Lethargic/Unconscious": "Checked: Lethargic/Unconscious",
        "Measurement Skills (Average)": "Measurement Skills (Average)",
        "Measurement Skills": "Measurement Skills",
        "Weight Measured Correctly": "Weight Measured Correctly",
        "Temp Measured Correctly": "Temp Measured Correctly",
        "Height Measured Correctly": "Height Measured Correctly",
        "Correct Respiratory Rate Measurement": "Correct Respiratory Rate Measurement",
        "Correct Respiratory Rate": "Correct Respiratory Rate",
        "Correct Dehydration assessment": "Correct Dehydration assessment",
        "Correct Malnutrition Assessment": "Correct Malnutrition Assessment",
        "MUAC Measured Correctly": "MUAC Measured Correctly",
        "Z-Score (WFH) Measured Correctly": "Z-Score (WFH) Measured Correctly",
        "Percentage of cases assessed for Immunization correctly": "Percentage of cases assessed for Immunization correctly",
        "Immunization Assessed Correctly": "Immunization Assessed Correctly",
        "Percentage of cases assessed for vitamin supplementation correctly": "Percentage of cases assessed for vitamin supplementation correctly",
        "Vitamin Supplementation Correctly": "Vitamin Supplementation Correctly",
        "Percentage of Pneumonia cases Treated correctly with Amoxicillin": "Percentage of Pneumonia cases Treated correctly with Amoxicillin",
        "Pneumonia Treated with Amoxicillin": "Pneumonia Treated with Amoxicillin",
        "Percentage of Diarrhea cases Treated with ORS": "Percentage of Diarrhea cases Treated with ORS",
        "Diarrhea Treated with ORS": "Diarrhea Treated with ORS",
        "Percentage of Diarrhea cases Treated with Zinc": "Percentage of Diarrhea cases Treated with Zinc",
        "Diarrhea Treated with Zinc": "Diarrhea Treated with Zinc",
        "Percentage of malaria cases treated with Coartum": "Percentage of malaria cases treated with Coartum",
        "Malaria Treated with Coartem": "Malaria Treated with Coartem",
        "Percentage of cases advised when to return immediately": "Percentage of cases advised when to return immediately",
        "Advised Return Immediately": "Advised Return Immediately",
        "Percentage of cases advised to return for follow up": "Percentage of cases advised to return for follow up",
        "Advised Return for Follow Up": "Advised Return for Follow Up",
        "Recording Form Use": "Recording Form Use",
        "Registering Signs": "Registering Signs",
        "Registering Classifications": "Registering Classifications",
        "Registering Treatments": "Registering Treatments",
        "Did health worker's decision match the supervisor's?": "Did health worker's decision match the supervisor's?",
        "KPI Summary by Job Description": "KPI Summary by Job Description",
        "Overall Adherence by": "Overall Adherence by",
        "Detailed Skill Performance": "Detailed Skill Performance",
        "Overall IMNCI Adherence": "Overall IMNCI Adherence",
        "Core Components Adherence": "Core Components Adherence",
        "Adherence Over Time (Danger Signs)": "Adherence Over Time (Danger Signs)",
        "Adherence Over Time (Measurement Skills)": "Adherence Over Time (Measurement Skills)",
        "Adherence Over Time (Malnutrition Signs)": "Adherence Over Time (Malnutrition Signs)",
        "Recording Form Use Over Time": "Recording Form Use Over Time",
        "Overall IMNCI Adherence by": "Overall IMNCI Adherence by",
        
        "Total Completed EENC Visits": "Total Completed EENC Visits",
        "Overall EENC Adherence Scores (Average)": "Overall EENC Adherence Scores (Average)",
        "Overall EENC Adherence": "Overall EENC Adherence",
        "Preparation Score": "Preparation Score",
        "Drying & Stimulation Score": "Drying & Stimulation Score",
        "Breathing Baby Mgmt Score": "Breathing Baby Mgmt Score",
        "Resuscitation Score": "Resuscitation Score",
        "EENC Adherence Over Time (Main KPIs)": "EENC Adherence Over Time (Main KPIs)",
        "KPI 1: Infection Control (All Cases)": "KPI 1: Infection Control (All Cases)",
        "Hand Washing (1st)": "Hand Washing (1st)",
        "Hand Washing (2nd)": "Hand Washing (2nd)",
        "Sterile Gloves Used": "Sterile Gloves Used",
        "KPI 1 Over Time: Infection Control": "KPI 1 Over Time: Infection Control",
        "KPI 2: Resuscitation Preparedness (All Cases)": "KPI 2: Resuscitation Preparedness (All Cases)",
        "Towels Prepared": "Towels Prepared",
        "Resus Equipment Ready": "Resus Equipment Ready",
        "Ambu Bag Checked": "Ambu Bag Checked",
        "KPI 2 Over Time: Preparedness": "KPI 2 Over Time: Preparedness",
        "KPI 3: Early Care (All Cases)": "KPI 3: Early Care (All Cases)",
        "Drying within 5 sec": "Drying within 5 sec",
        "Immediate Skin-to-Skin": "Immediate Skin-to-Skin",
        "Dry Towel & Hat Used": "Dry Towel & Hat Used",
        "KPI 3 Over Time: Early Care": "KPI 3 Over Time: Early Care",
        "KPI 4: Cord Management (Breathing Babies)": "KPI 4: Cord Management (Breathing Babies)",
        "Hygienic Cord Check": "Hygienic Cord Check",
        "Delayed Clamping": "Delayed Clamping",
        "Correct Clamping": "Correct Clamping",
        "KPI 4 Over Time: Cord Mgmt": "KPI 4 Over Time: Cord Mgmt",
        "KPI 5: Breastfeeding (Breathing Babies)": "KPI 5: Breastfeeding (Breathing Babies)",
        "Early Breastfeeding Advice": "Early Breastfeeding Advice",
        "KPI 5 Over Time: Breastfeeding": "KPI 5 Over Time: Breastfeeding",
        "KPI 6: Resuscitation Execution (Non-Breathing)": "KPI 6: Resuscitation Execution (Non-Breathing)",
        "Head Positioning": "Head Positioning",
        "Good Mask Seal": "Good Mask Seal",
        "Chest Rise (1st min)": "Chest Rise (1st min)",
        "Adequate Rate (30-50)": "Adequate Rate (30-50)",
        "KPI 6 Over Time: Resuscitation": "KPI 6 Over Time: Resuscitation",
        "Overall EENC Adherence by": "Overall EENC Adherence by",
        "Detailed EENC Skill Performance": "Detailed EENC Skill Performance",

        // --- Detailed Provider Skills Group Names & Values ---
        "Assessment & Classification Skills": "Assessment & Classification Skills",
        "Treatment & Counseling Skills": "Treatment & Counseling Skills",
        "Recording Skills": "Recording Skills",
        "Physical & Vital Measurements": "Physical & Vital Measurements",
        "General Danger Signs Assessment": "General Danger Signs Assessment",
        "Main Symptoms Assessment": "Main Symptoms Assessment",
        "Acute Malnutrition Assessment": "Acute Malnutrition Assessment",
        "Anemia Assessment": "Anemia Assessment",
        "Immunization & Vitamin A Assessment": "Immunization & Vitamin A Assessment",
        "Other Problems Assessment": "Other Problems Assessment",
        "Referral Cases Management": "Referral Cases Management",
        "Pneumonia Management": "Pneumonia Management",
        "Diarrhea Management": "Diarrhea Management",
        "Dysentery Management": "Dysentery Management",
        "Malaria Management": "Malaria Management",
        "Ear Infection Management": "Ear Infection Management",
        "Malnutrition Management": "Malnutrition Management",
        "Anemia Management": "Anemia Management",
        "Follow-up Counseling": "Follow-up Counseling",
        "Data Recording": "Data Recording",
        "Weighed the child correctly": "Weighed the child correctly",
        "Measured temperature correctly": "Measured temperature correctly",
        "Measured height/length correctly": "Measured height/length correctly",
        "Asked about cough or difficult breathing": "Asked about cough or difficult breathing",
        "Counted respiratory rate correctly": "Counted respiratory rate correctly",
        "Classified cough correctly": "Classified cough correctly",
        "Asked about diarrhea": "Asked about diarrhea",
        "Assessed dehydration correctly": "Assessed dehydration correctly",
        "Classified diarrhea correctly": "Classified diarrhea correctly",
        "Asked about fever": "Asked about fever",
        "Performed RDT correctly": "Performed RDT correctly",
        "Classified fever correctly": "Classified fever correctly",
        "Asked about ear problem": "Asked about ear problem",
        "Checked for tender swelling behind the ear": "Checked for tender swelling behind the ear",
        "Classified ear problem correctly": "Classified ear problem correctly",
        "Measured MUAC correctly": "Measured MUAC correctly",
        "Measured WFH z-score correctly": "Measured WFH z-score correctly",
        "Classified nutritional status correctly": "Classified nutritional status correctly",
        "Checked for palmar pallor correctly": "Checked for palmar pallor correctly",
        "Classified anemia correctly": "Classified anemia correctly",
        "Checked immunizations correctly": "Checked immunizations correctly",
        "Checked Vitamin A correctly": "Checked Vitamin A correctly",
        "Checked for other problems": "Checked for other problems",
        "Gave 1st dose of appropriate antibiotic before referral": "Gave 1st dose of appropriate antibiotic before referral",
        "Gave IM Quinine before referral (if applicable)": "Gave IM Quinine before referral (if applicable)",
        "Prescribed Amoxicillin correctly": "Prescribed Amoxicillin correctly",
        "Gave 1st dose of Amoxicillin in clinic": "Gave 1st dose of Amoxicillin in clinic",
        "Determined ORS amount correctly": "Determined ORS amount correctly",
        "Counseled mother on home care (fluids/feeding)": "Counseled mother on home care (fluids/feeding)",
        "Prescribed Zinc correctly": "Prescribed Zinc correctly",
        "Gave 1st dose of Zinc in clinic": "Gave 1st dose of Zinc in clinic",
        "Prescribed Ciprofloxacin correctly": "Prescribed Ciprofloxacin correctly",
        "Gave 1st dose of Ciprofloxacin in clinic": "Gave 1st dose of Ciprofloxacin in clinic",
        "Prescribed Coartem (ACT) correctly": "Prescribed Coartem (ACT) correctly",
        "Gave 1st dose of Coartem in clinic": "Gave 1st dose of Coartem in clinic",
        "Prescribed Amoxicillin for ear infection": "Prescribed Amoxicillin for ear infection",
        "Gave 1st dose of Amoxicillin for ear infection in clinic": "Gave 1st dose of Amoxicillin for ear infection in clinic",
        "Prescribed Paracetamol correctly": "Prescribed Paracetamol correctly",
        "Gave 1st dose of Paracetamol in clinic": "Gave 1st dose of Paracetamol in clinic",
        "Referred child to OTP": "Referred child to OTP",
        "Assessed feeding including breastfeeding problems": "Assessed feeding including breastfeeding problems",
        "Counseled mother on feeding including breastfeeding": "Counseled mother on feeding including breastfeeding",
        "Prescribed Iron syrup correctly": "Prescribed Iron syrup correctly",
        "Gave 1st dose of Iron syrup in clinic": "Gave 1st dose of Iron syrup in clinic",
        "Advised on at least 2 signs to return immediately": "Advised on at least 2 signs to return immediately",
        "Specified when to return for follow-up": "Specified when to return for follow-up",
        "Recorded signs correctly": "Recorded signs correctly",
        "Recorded classifications correctly": "Recorded classifications correctly",
        "Recorded treatments correctly": "Recorded treatments correctly",

        "Hand washing": "Hand washing",
        "Second hand washing": "Second hand washing",
        "Sterile gloves": "Sterile gloves",
        "Towels prepared": "Towels prepared",
        "Resuscitation area prepared": "Resuscitation area prepared",
        "Ambu bag checked": "Ambu bag checked",
        "Drying started within 5s": "Drying started within 5s",
        "Skin-to-skin contact": "Skin-to-skin contact",
        "Baby covered with dry towel/hat": "Baby covered with dry towel/hat",
        "Hygienic cord check": "Hygienic cord check",
        "Delayed cord clamping": "Delayed cord clamping",
        "Correct cord clamping": "Correct cord clamping",
        "Early breastfeeding advice": "Early breastfeeding advice",
        "Head positioned correctly": "Head positioned correctly",
        "Correct mask placement": "Correct mask placement",
        "Chest rise checked": "Chest rise checked",
        "Ventilation rate 30-50/min": "Ventilation rate 30-50/min",

        // --- IMNCI Training Skill Groups ---
        "Number of training sessions on use of IMNCI tools": "Number of training sessions on use of IMNCI tools",
        "Number of training sessions on Main IMNCI Signs Assessment": "Number of training sessions on Main IMNCI Signs Assessment",
        "Number of training sessions on Malnutrition signs Assessment": "Number of training sessions on Malnutrition signs Assessment",
        "Chartbooklet use training sessions": "Chartbooklet use training sessions",
        "Mother Counseling Card use training sessions": "Mother Counseling Card use training sessions",
        "Recording Form filling training sessions": "Recording Form filling training sessions",
        "Daily and Monthly Statistic Reports filling training sessions": "Daily and Monthly Statistic Reports filling training sessions",
        "Danger Signs assessment training sessions": "Danger Signs assessment training sessions",
        "Respiratory Rate measurement training sessions": "Respiratory Rate measurement training sessions",
        "Dehydration assessment training sessions": "Dehydration assessment training sessions",
        "Immunization check training sessions": "Immunization check training sessions",
        "Weight measurement training sessions": "Weight measurement training sessions",
        "Height measurement training sessions": "Height measurement training sessions",
        "MUAC measurement training sessions": "MUAC measurement training sessions",
        "Z-Score measurement training sessions": "Z-Score measurement training sessions",
        "Lower Limb Edema check training sessions": "Lower Limb Edema check training sessions",

        // --- EENC specific Skills Labels ---
        "Hand Washing": "Hand Washing",
        "Equipment Preparation": "Equipment Preparation",
        "Drying": "Drying",
        "Skin-to-Skin Contact": "Skin-to-Skin Contact",
        "Suctioning": "Suctioning",
        "Cord Pulse Check": "Cord Pulse Check",
        "Clamp Placement": "Clamp Placement",
        "Baby Transfer": "Baby Transfer",
        "Opening Airway": "Opening Airway",
        "Ambu Bag Placement": "Ambu Bag Placement",
        "Ambu Bag Use": "Ambu Bag Use",
        "Ventilation Rate": "Ventilation Rate",
        "Corrective Steps": "Corrective Steps",

        // --- Chart Legend Short Titles ---
        "Meds": "Meds", "Tx": "Tx", "Return": "Return", "Fluids": "Fluids", "Rules": "Rules", "Time": "Time", "Comm": "Comm", "Learned": "Learned",
        "Imm. S2S": "Imm. S2S", "90min S2S": "90min S2S", "1st Hr": "1st Hr", "Subs": "Subs", "Bottle": "Bottle", "Vit K": "Vit K", "Eye": "Eye", "Cord Sub": "Cord Sub", "Oiling": "Oiling", "Bath <6h": "Bath <6h", "Polio": "Polio", "BCG": "BCG", "Weight": "Weight", "Temp": "Temp", "Civil Reg": "Civil Reg", "Card": "Card",
        "Overall": "Overall", "Assessment": "Assessment", "Decision": "Decision", "Treatment": "Treatment", "Danger Signs Score": "Danger Signs Score", "Measurement Skills Average": "Measurement Skills Average", "Resp. Rate": "Resp. Rate", "Dehydration": "Dehydration", "Malnutrition Assessment": "Malnutrition Assessment", "Immunization": "Immunization", "Vitamin Assessment": "Vitamin Assessment", "Coartem (ACT)": "Coartem (ACT)", "Return Immediately": "Return Immediately", "Return Followup": "Return Followup", "Signs": "Signs", "Classifications": "Classifications", "Treatments": "Treatments", "Preparation": "Preparation", "Breathing Mgmt": "Breathing Mgmt", "Hand Wash 1": "Hand Wash 1", "Hand Wash 2": "Hand Wash 2", "Gloves": "Gloves", "Towels": "Towels", "Equip Ready": "Equip Ready", "Ambu Check": "Ambu Check", "Drying < 5s": "Drying < 5s", "Towel/Hat": "Towel/Hat", "Hygienic Check": "Hygienic Check", "Delayed Clamp": "Delayed Clamp", "Correct Clamp": "Correct Clamp", "BF Advice": "BF Advice", "Head Pos": "Head Pos", "Mask Seal": "Mask Seal", "Chest Rise": "Chest Rise", "Rate": "Rate",

        // --- Mother Interviews ---
        "Total Mother Interviews": "Total Mother Interviews",
        "Mother Knowledge: Treatment": "Mother Knowledge: Treatment",
        "Knows Med Details": "Knows Med Details",
        "Knows Treatment Details": "Knows Treatment Details",
        "Knows Return Date": "Knows Return Date",
        "Knowledge (Meds) Over Time": "Knowledge (Meds) Over Time",
        "Mother Knowledge: ORS & Fluids": "Mother Knowledge: ORS & Fluids",
        "Knows ORS Prep": "Knows ORS Prep",
        "Knows Home Fluids": "Knows Home Fluids",
        "Knows 4 Rules": "Knows 4 Rules",
        "Knowledge (ORS) Over Time": "Knowledge (ORS) Over Time",
        "Mother Satisfaction": "Mother Satisfaction",
        "Satisfaction: Time Spent": "Satisfaction: Time Spent",
        "Satisfaction: Communication": "Satisfaction: Communication",
        "Satisfaction: Learned Something": "Satisfaction: Learned Something",
        "Satisfaction Over Time": "Satisfaction Over Time",
        "Overall Mother Interview Scores by": "Overall Mother Interview Scores by",
        "Average Mother Knowledge/Satisfaction by": "Average Mother Knowledge/Satisfaction by",
        "Detailed Mother Interview Performance": "Detailed Mother Interview Performance",
        
        "Mother Interview: Skin-to-Skin Care": "Mother Interview: Skin-to-Skin Care",
        "Uninterrupted 90min S2S": "Uninterrupted 90min S2S",
        "Skin-to-Skin Over Time": "Skin-to-Skin Over Time",
        "Mother Interview: Breastfeeding": "Mother Interview: Breastfeeding",
        "Feeding in 1st Hour": "Feeding in 1st Hour",
        "Given Substitutes (Yes)": "Given Substitutes (Yes)",
        "Feeding with Bottle (Yes)": "Feeding with Bottle (Yes)",
        "Breastfeeding Over Time": "Breastfeeding Over Time",
        "Mother Interview: Skin & Cord Care": "Mother Interview: Skin & Cord Care",
        "Vitamin K Given": "Vitamin K Given",
        "Eye Ointment Given": "Eye Ointment Given",
        "Cord Substance Applied": "Cord Substance Applied",
        "Care Indicators Over Time": "Care Indicators Over Time",
        "Mother Interview: Oiling & Bathing": "Mother Interview: Oiling & Bathing",
        "Skin Oiling (Yes)": "Skin Oiling (Yes)",
        "Bathing < 6hrs (Yes)": "Bathing < 6hrs (Yes)",
        "Hygiene Indicators Over Time": "Hygiene Indicators Over Time",
        "Mother Interview: Vaccination": "Mother Interview: Vaccination",
        "Polio Vaccine (Zero)": "Polio Vaccine (Zero)",
        "BCG Vaccine": "BCG Vaccine",
        "Vaccination Over Time": "Vaccination Over Time",
        "Mother Interview: Measurements": "Mother Interview: Measurements",
        "Weight Measured": "Weight Measured",
        "Temp Measured": "Temp Measured",
        "Measurements Over Time": "Measurements Over Time",
        "Mother Interview: Registration": "Mother Interview: Registration",
        "Civil Registration": "Civil Registration",
        "Discharge Card Given": "Discharge Card Given",
        "Registration Over Time": "Registration Over Time",
        "Overall Mother Interview Indicators by": "Overall Mother Interview Indicators by",
        "Average Indicator Presence by": "Average Indicator Presence by",

        // --- Mother Survey Detailed Sentences (EN) ---
        "Mother knows medication details (dose, frequency, days)": "Mother knows medication details (dose, frequency, days)",
        "Mother knows combination treatment details": "Mother knows combination treatment details",
        "Mother knows the 4 rules for home diarrhea management": "Mother knows the 4 rules for home diarrhea management",
        "Mother knows follow-up return date": "Mother knows follow-up return date",
        "Mother knows how to prepare ORS": "Mother knows how to prepare ORS",
        "Mother knows allowed home fluids": "Mother knows allowed home fluids",
        "Mother knows correct water quantity for ORS": "Mother knows correct water quantity for ORS",
        "Mother knows ORS amount to give after each stool": "Mother knows ORS amount to give after each stool",
        "Satisfaction with time spent by health worker": "Satisfaction with time spent by health worker",
        "Satisfaction with assessment method": "Satisfaction with assessment method",
        "Satisfaction with given treatment": "Satisfaction with given treatment",
        "Satisfaction with communication style": "Satisfaction with communication style",
        "Satisfaction with what was learned": "Satisfaction with what was learned",
        "Satisfaction with drug availability at facility": "Satisfaction with drug availability at facility",
        "Baby placed skin-to-skin immediately after birth?": "Baby placed skin-to-skin immediately after birth?",
        "Baby kept skin-to-skin continuously for 90 minutes?": "Baby kept skin-to-skin continuously for 90 minutes?",
        "Baby completed a full feed within first hour?": "Baby completed a full feed within first hour?",
        "Baby given any fluids other than breastmilk?": "Baby given any fluids other than breastmilk?",
        "Baby given any fluids via bottle?": "Baby given any fluids via bottle?",
        "Baby given Vitamin K?": "Baby given Vitamin K?",
        "Baby given Tetracycline eye ointment?": "Baby given Tetracycline eye ointment?",
        "Anything applied to the cord?": "Anything applied to the cord?",
        "Baby rubbed with oil?": "Baby rubbed with oil?",
        "Baby bathed?": "Baby bathed?",
        "Baby given zero-dose Polio vaccine?": "Baby given zero-dose Polio vaccine?",
        "Baby given BCG vaccine?": "Baby given BCG vaccine?",
        "Baby weighed?": "Baby weighed?",
        "Baby temperature measured?": "Baby temperature measured?",
        "Baby registered in civil registry?": "Baby registered in civil registry?",
        "Baby given discharge card?": "Baby given discharge card?",

        // --- Visit Reports ---
        "Total Visit Reports": "Total Visit Reports",
        "Total Number of Training Sessions": "Total Number of Training Sessions",
        "mean sessions per visit": "mean sessions per visit",
        "Note: To view Information System and Drug Shortage data, ensure rawReports is included.": "Note: To view Information System and Drug Shortage data, ensure rawReports is included.",
        "Information System KPIs (Overall)": "Information System KPIs (Overall)",
        "Children seen by IMNCI trained cadre": "Children seen by IMNCI trained cadre",
        "Children with IMNCI recording form": "Children with IMNCI recording form",
        "Children returning for follow up": "Children returning for follow up",
        "total": "total",
        "trained": "trained",
        "Visit": "Visit",
        "Seen by Trained Cadre (%)": "Seen by Trained Cadre (%)",
        "With Recording Form (%)": "With Recording Form (%)",
        "Return for Follow-up (%)": "Return for Follow-up (%)",
        "Information System Performance Over Time": "Information System Performance Over Time",
        "KPI Performance (%)": "KPI Performance (%)",
        "Facility Drug Availability (Percentage of facilities reporting drugs always available)": "Facility Drug Availability (Percentage of facilities reporting drugs always available)",
        "Amoxicillin": "Amoxicillin",
        "Zinc": "Zinc",
        "ORS": "ORS",
        "Coartem": "Coartem",
        "Availability": "Availability",
        "of": "of",
        "facilities": "facilities",
        "Drug Availability Over Time": "Drug Availability Over Time",
        "Facilities with Drug Available (%)": "Facilities with Drug Available (%)",
        "Times Trained": "Times Trained",
        "% of Total Training Sessions": "% of Total Training Sessions",
        "No training data recorded.": "No training data recorded.",
        "Visit Breakdown & Skills Trained by Facility": "Visit Breakdown & Skills Trained by Facility",
        "Facility": "Facility",
        "No visits found for current filter.": "No visits found for current filter.",
        "Total Visits by": "Total Visits by",
        "Facility Problems & Solutions (Combined)": "Facility Problems & Solutions (Combined)",
        "Problem / Challenge": "Problem / Challenge",
        "Implemented Solution": "Implemented Solution",
        "Status": "Status",
        "Responsible Person": "Responsible Person",
        "No problems recorded.": "No problems recorded."
    },
    ar: {
        // --- General & App ---
        "app.title": "لوحة متابعة الإشراف",
        "tab.skills": "مراقبة المهارات (مقدم الخدمة)",
        "tab.mothers": "مقابلات الأمهات",
        "tab.visit_reports": "تقارير الزيارات (المؤسسة)",
        "tab.admin": "لوحة تحكم المشرف",
        "btn.refresh": "تحديث",
        "btn.back": "العودة للقائمة الرئيسية",
        
        // --- Filters ---
        "filter.date": "تصفية حسب التاريخ",
        "filter.state": "الولاية",
        "filter.locality": "المحلية",
        "filter.facility": "المؤسسة الصحية",
        "filter.project": "المشروع / الشريك",
        "filter.job_title": "الوصف الوظيفي",
        "filter.worker_name": "اسم العامل الصحي",
        
        "filter.all.time": "كل الأوقات",
        "filter.all.states": "كل الولايات",
        "filter.all.localities": "كل المحليات",
        "filter.all.facilities": "كل المؤسسات",
        "filter.all.projects": "كل المشاريع",
        "filter.all.titles": "كل الوظائف",
        "filter.all.workers": "كل الكوادر",
        
        // --- Dates ---
        "date.today": "اليوم",
        "date.yesterday": "الأمس",
        "date.this_week": "هذا الأسبوع",
        "date.last_week": "الأسبوع الماضي",
        "date.this_month": "هذا الشهر",
        "date.last_month": "الشهر الماضي",
        "date.this_year": "هذا العام",
        "date.last_year": "العام الماضي",

        // --- Messages ---
        "msg.loading": "جاري تحميل بيانات اللوحة...",
        "msg.please_wait": "يرجى الانتظار بينما نقوم بجلب أحدث السجلات.",
        "msg.filtered_by": "تمت التصفية حسب",
        "msg.all_sudan": "بيانات كل السودان",
        
        // --- Shared Tables & KPIs ---
        "Copy as Image": "نسخ كصورة",
        "Value": "القيمة",
        "Count": "العدد",
        "Percentage": "النسبة المئوية",
        "Skill": "المهارة",
        "Skill (EENC)": "المهارة (EENC)",
        "Count (Yes / Total)": "العدد (نعم / المجموع)",
        "Count (Yes / Partial / No)": "العدد (نعم / جزئي / لا)",
        "Question (Mother Survey)": "السؤال (استبيان الأم)",
        "KPI Name": "مؤشر الأداء",
        "Overall Score": "الدرجة الكلية",
        "Total Completed Visits": "إجمالي الزيارات المكتملة",
        "Visits per HW": "زيارات لكل عامل",
        "Total HWs Visited": "إجمالي الكوادر",
        "Total Cases Observed": "إجمالي الحالات المراقبة",
        "Cases per Visit": "حالات لكل زيارة",
        "Mentor Name": "اسم المشرف",
        "Health Workers": "الكوادر الصحية",
        "Mother Forms": "استبيانات الأمهات",
        "Forms per Visit": "استبيان لكل زيارة",
        "Visit Reports": "تقارير الزيارات",
        "% of Completed Visits": "% من الزيارات المكتملة",
        "No detailed skill data available.": "لا توجد بيانات تفصيلية للمهارات.",
        "No detailed EENC skill data available.": "لا توجد بيانات تفصيلية لمهارات EENC.",
        "No mother survey data available.": "لا توجد بيانات لاستبيان الأمهات.",
        "No data available.": "لا توجد بيانات متاحة.",
        "Yes": "نعم",
        "Partial": "جزئي",
        "No": "لا",
        "submitted": "مُقدم",
        "visits/hw": "زيارة/عامل",
        "cases/visit": "حالة/زيارة",
        "forms/visit": "استبيان/زيارة",

        // --- Job Titles ---
        "Medical Officer": "طبيب عمومي",
        "Medical Assistant": "مساعد طبي",
        "Nurse": "ممرض",
        "Midwife": "قابلة",
        "Unknown Title": "غير محدد",

        // --- Visit Numbers ---
        "Visit 1": "الزيارة الأولى",
        "Visit 2": "الزيارة الثانية",
        "Visit 3": "الزيارة الثالثة",
        "Visit 4": "الزيارة الرابعة",
        "Visit 5": "الزيارة الخامسة",
        "Visit 6": "الزيارة السادسة",

        // --- Dashboard Labels ---
        "State": "الولاية",
        "Locality": "المحلية",
        "Facility & Date": "المؤسسة والتاريخ",
        "Integrated Management of Newborn and Childhood Illnesses (IMNCI)": "المعالجة المتكاملة لأمراض الطفولة وحديثي الولادة (IMNCI)",
        "Early Essential Newborn Care (EENC)": "الرعاية الأساسية المبكرة لحديثي الولادة (EENC)",
        "Infection Control": "مكافحة العدوى",
        "Cord Management (Breathing Babies)": "العناية بالحبل السري (للحالات المستقرة)",

        // --- Provider Skills (IMNCI & EENC) ---
        "Overall Adherence Score": "درجة الالتزام الكلية",
        "Assess & Classify": "التقييم والتصنيف",
        "Final Decision": "القرار النهائي",
        "Treatment & Counsel": "العلاج والنصح",
        "Danger Signs Assessment": "تقييم علامات الخطورة",
        "Asked/Checked: Cannot Drink/Breastfeed": "سأل/فحص: لا يستطيع الشرب أو الرضاعة",
        "Asked/Checked: Vomits Everything": "سأل/فحص: يتقيأ كل شيء",
        "Asked/Checked: Convulsions": "سأل/فحص: تشنجات",
        "Checked: Lethargic/Unconscious": "فحص: خمول أو فقدان وعي",
        "Measurement Skills (Average)": "مهارات القياس (متوسط)",
        "Measurement Skills": "مهارات القياس",
        "Weight Measured Correctly": "تم قياس الوزن بشكل صحيح",
        "Temp Measured Correctly": "تم قياس الحرارة بشكل صحيح",
        "Height Measured Correctly": "تم قياس الطول بشكل صحيح",
        "Correct Respiratory Rate Measurement": "القياس الصحيح لمعدل التنفس",
        "Correct Respiratory Rate": "قياس معدل التنفس بشكل صحيح",
        "Correct Dehydration assessment": "التقييم الصحيح للجفاف",
        "Correct Malnutrition Assessment": "التقييم الصحيح لسوء التغذية",
        "MUAC Measured Correctly": "تم قياس MUAC بشكل صحيح",
        "Z-Score (WFH) Measured Correctly": "تم قياس Z-Score بشكل صحيح",
        "Percentage of cases assessed for Immunization correctly": "نسبة الحالات التي تم تقييم التطعيم لها بشكل صحيح",
        "Immunization Assessed Correctly": "تم تقييم التطعيم بشكل صحيح",
        "Percentage of cases assessed for vitamin supplementation correctly": "نسبة الحالات التي تم تقييم فيتامين أ لها بشكل صحيح",
        "Vitamin Supplementation Correctly": "تم تقييم فيتامين أ بشكل صحيح",
        "Percentage of Pneumonia cases Treated correctly with Amoxicillin": "نسبة حالات الالتهاب الرئوي المعالجة بالأموكسيسيلين",
        "Pneumonia Treated with Amoxicillin": "معالجة الالتهاب الرئوي بالأموكسيسيلين",
        "Percentage of Diarrhea cases Treated with ORS": "نسبة حالات الإسهال المعالجة بأملاح التروية",
        "Diarrhea Treated with ORS": "معالجة الإسهال بأملاح التروية",
        "Percentage of Diarrhea cases Treated with Zinc": "نسبة حالات الإسهال المعالجة بالزنك",
        "Diarrhea Treated with Zinc": "معالجة الإسهال بالزنك",
        "Percentage of malaria cases treated with Coartum": "نسبة حالات الملاريا المعالجة بالكورتيم",
        "Malaria Treated with Coartem": "معالجة الملاريا بالكورتيم",
        "Percentage of cases advised when to return immediately": "نسبة الحالات التي تم نصحها متى تعود فوراً",
        "Advised Return Immediately": "تم النصح بالعودة فوراً",
        "Percentage of cases advised to return for follow up": "نسبة الحالات التي تم نصحها بالعودة للمتابعة",
        "Advised Return for Follow Up": "تم النصح بالعودة للمتابعة",
        "Recording Form Use": "استخدام استمارة التسجيل",
        "Registering Signs": "تسجيل العلامات",
        "Registering Classifications": "تسجيل التصنيفات",
        "Registering Treatments": "تسجيل العلاج",
        "Did health worker's decision match the supervisor's?": "هل طابق قرار العامل الصحي قرار المشرف؟",
        "KPI Summary by Job Description": "ملخص مؤشرات الأداء حسب الوصف الوظيفي",
        "Overall Adherence by": "الالتزام الكلي حسب",
        "Detailed Skill Performance": "الأداء التفصيلي للمهارات",
        "Overall IMNCI Adherence": "الالتزام الكلي (IMNCI)",
        "Core Components Adherence": "الالتزام بالمكونات الأساسية",
        "Adherence Over Time (Danger Signs)": "الالتزام بمرور الوقت (علامات الخطورة)",
        "Adherence Over Time (Measurement Skills)": "الالتزام بمرور الوقت (مهارات القياس)",
        "Adherence Over Time (Malnutrition Signs)": "الالتزام بمرور الوقت (علامات سوء التغذية)",
        "Recording Form Use Time": "استخدام الاستمارة بمرور الوقت",
        "Overall IMNCI Adherence by": "الالتزام الكلي (IMNCI) حسب",
        
        "Total Completed EENC Visits": "إجمالي زيارات EENC المكتملة",
        "Overall EENC Adherence Scores (Average)": "الالتزام الكلي (EENC) (متوسط)",
        "Overall EENC Adherence": "الالتزام الكلي (EENC)",
        "Preparation Score": "درجة التحضير",
        "Drying & Stimulation Score": "درجة التجفيف والتحفيز",
        "Breathing Baby Mgmt Score": "درجة إدارة الطفل الذي يتنفس",
        "Resuscitation Score": "درجة الإنعاش",
        "EENC Adherence Over Time (Main KPIs)": "الالتزام بمرور الوقت (EENC المكونات الأساسية)",
        "KPI 1: Infection Control (All Cases)": "مؤشر 1: مكافحة العدوى (كل الحالات)",
        "Hand Washing (1st)": "غسل اليدين (الأول)",
        "Hand Washing (2nd)": "غسل اليدين (الثاني)",
        "Sterile Gloves Used": "استخدام قفازات معقمة",
        "KPI 1 Over Time: Infection Control": "مؤشر 1 بمرور الوقت: مكافحة العدوى",
        "KPI 2: Resuscitation Preparedness (All Cases)": "مؤشر 2: جاهزية الإنعاش (كل الحالات)",
        "Towels Prepared": "تجهيز المناشف",
        "Resus Equipment Ready": "تجهيز معدات الإنعاش",
        "Ambu Bag Checked": "فحص حقيبة الإنعاش",
        "KPI 2 Over Time: Preparedness": "مؤشر 2 بمرور الوقت: الجاهزية",
        "KPI 3: Early Care (All Cases)": "مؤشر 3: الرعاية المبكرة (كل الحالات)",
        "Drying within 5 sec": "التجفيف خلال 5 ثواني",
        "Immediate Skin-to-Skin": "تلامس الجلد للجلد فوراً",
        "Dry Towel & Hat Used": "استخدام منشفة جافة وقبعة",
        "KPI 3 Over Time: Early Care": "مؤشر 3 بمرور الوقت: الرعاية المبكرة",
        "KPI 4: Cord Management (Breathing Babies)": "مؤشر 4: العناية بالحبل السري",
        "Hygienic Cord Check": "فحص الحبل السري بنظافة",
        "Delayed Clamping": "تأخير قطع الحبل السري",
        "Correct Clamping": "القطع الصحيح",
        "KPI 4 Over Time: Cord Mgmt": "مؤشر 4 بمرور الوقت: العناية بالحبل السري",
        "KPI 5: Breastfeeding (Breathing Babies)": "مؤشر 5: الرضاعة الطبيعية",
        "Early Breastfeeding Advice": "النصح المبكر بالرضاعة",
        "KPI 5 Over Time: Breastfeeding": "مؤشر 5 بمرور الوقت: الرضاعة",
        "KPI 6: Resuscitation Execution (Non-Breathing)": "مؤشر 6: تنفيذ الإنعاش",
        "Head Positioning": "تعديل وضعية الرأس",
        "Good Mask Seal": "إحكام القناع",
        "Chest Rise (1st min)": "ارتفاع الصدر",
        "Adequate Rate (30-50)": "معدل التنفس (30-50)",
        "KPI 6 Over Time: Resuscitation": "مؤشر 6 بمرور الوقت: الإنعاش",
        "Overall EENC Adherence by": "الالتزام الكلي (EENC) حسب",
        "Detailed EENC Skill Performance": "الأداء التفصيلي لمهارات EENC",

        // --- Detailed Provider Skills Group Names & Values ---
        "Assessment & Classification Skills": "تقييم مهارات التقييم والتصنيف",
        "Treatment & Counseling Skills": "تقييم مهارات العلاج والنصح",
        "Recording Skills": "استخدام الاستمارة",
        "Physical & Vital Measurements": "القياسات الجسمانية والحيوية",
        "General Danger Signs Assessment": "تقييم علامات الخطورة العامة",
        "Main Symptoms Assessment": "تقييم الأعراض الأساسية",
        "Acute Malnutrition Assessment": "التحري عن سوء التغذية الحاد",
        "Anemia Assessment": "التحري عن الانيميا",
        "Immunization & Vitamin A Assessment": "التطعيم وفيتامين أ",
        "Other Problems Assessment": "الأمراض الأخرى",
        "Referral Cases Management": "إدارة الحالات المحولة",
        "Pneumonia Management": "علاج الإلتهاب الرئوي",
        "Diarrhea Management": "علاج الإسهال",
        "Dysentery Management": "علاج الدسنتاريا",
        "Malaria Management": "علاج الملاريا",
        "Ear Infection Management": "علاج التهاب الأذن",
        "Malnutrition Management": "علاج سوء التغذية",
        "Anemia Management": "علاج فقر الدم",
        "Follow-up Counseling": "نصح المتابعة",
        "Data Recording": "تسجيل البيانات",
        "Weighed the child correctly": "وزن الطفل بصورة صحيحة",
        "Measured temperature correctly": "قياس الحرارة بصورة صحيحة",
        "Measured height/length correctly": "قياس الطول بصورة صحيحة",
        "Asked about cough or difficult breathing": "سأل عن الكحة أو صعوبة التنفس",
        "Counted respiratory rate correctly": "حساب معدل التنفس بصورة صحيحة",
        "Classified cough correctly": "تصنيف الكحة بصورة صحيحة",
        "Asked about diarrhea": "سأل عن الإسهال",
        "Assessed dehydration correctly": "تقييم الجفاف بصورة صحيحة",
        "Classified diarrhea correctly": "تصنيف الإسهال بصورة صحيحة",
        "Asked about fever": "سأل عن الحمى",
        "Performed RDT correctly": "إجراء فحص الملاريا السريع",
        "Classified fever correctly": "تصنيف الحمى بصورة صحيحة",
        "Asked about ear problem": "سأل عن مشكلة الأذن",
        "Checked for tender swelling behind the ear": "فحص التورم خلف الأذن",
        "Classified ear problem correctly": "تصنيف مشكلة الأذن بصورة صحيحة",
        "Measured MUAC correctly": "قياس MUAC بصورة صحيحة",
        "Measured WFH z-score correctly": "قياس Z-Score بصورة صحيحة",
        "Classified nutritional status correctly": "تصنيف حالة التغذية بصورة صحيحة",
        "Checked for palmar pallor correctly": "فحص شحوب الكف بصورة صحيحة",
        "Classified anemia correctly": "تصنيف الانيميا بصورة صحيحة",
        "Checked immunizations correctly": "فحص التطعيمات بصورة صحيحة",
        "Checked Vitamin A correctly": "فحص فيتامين أ بصورة صحيحة",
        "Checked for other problems": "فحص المشاكل الأخرى",
        "Gave 1st dose of appropriate antibiotic before referral": "إعطاء جرعة أولى من المضاد الحيوي قبل التحويل",
        "Gave IM Quinine before referral (if applicable)": "إعطاء الكينين العضلي قبل التحويل",
        "Prescribed Amoxicillin correctly": "وصف الأموكسيسيلين بصورة صحيحة",
        "Gave 1st dose of Amoxicillin in clinic": "إعطاء جرعة أموكسيسيلين في العيادة",
        "Determined ORS amount correctly": "تحديد كمية أملاح التروية بصورة صحيحة",
        "Counseled mother on home care (fluids/feeding)": "نصح الأم بالرعاية المنزلية",
        "Prescribed Zinc correctly": "وصف الزنك بصورة صحيحة",
        "Gave 1st dose of Zinc in clinic": "إعطاء جرعة زنك في العيادة",
        "Prescribed Ciprofloxacin correctly": "وصف السيبروفلوكساسين بصورة صحيحة",
        "Gave 1st dose of Ciprofloxacin in clinic": "إعطاء جرعة سيبروفلوكساسين في العيادة",
        "Prescribed Coartem (ACT) correctly": "وصف الكورتيم بصورة صحيحة",
        "Gave 1st dose of Coartem in clinic": "إعطاء جرعة كورتيم في العيادة",
        "Prescribed Amoxicillin for ear infection": "وصف أموكسيسيلين لالتهاب الأذن",
        "Gave 1st dose of Amoxicillin for ear infection in clinic": "إعطاء جرعة أموكسيسيلين للأذن في العيادة",
        "Prescribed Paracetamol correctly": "وصف الباراسيتامول بصورة صحيحة",
        "Gave 1st dose of Paracetamol in clinic": "إعطاء جرعة باراسيتامول في العيادة",
        "Referred child to OTP": "تحويل الطفل للتغذية العلاجية (OTP)",
        "Assessed feeding including breastfeeding problems": "تقييم التغذية ومشاكل الرضاعة",
        "Counseled mother on feeding including breastfeeding": "نصح الأم بالتغذية والرضاعة",
        "Prescribed Iron syrup correctly": "وصف شراب الحديد بصورة صحيحة",
        "Gave 1st dose of Iron syrup in clinic": "إعطاء جرعة حديد في العيادة",
        "Advised on at least 2 signs to return immediately": "نصح بعلامتين للعودة فوراً",
        "Specified when to return for follow-up": "تحديد موعد العودة للمتابعة",
        "Recorded signs correctly": "تسجيل العلامات بصورة صحيحة",
        "Recorded classifications correctly": "تسجيل التصنيفات بصورة صحيحة",
        "Recorded treatments correctly": "تسجيل العلاجات بصورة صحيحة",

        "Hand washing": "غسل اليدين",
        "Second hand washing": "غسل اليدين للمرة الثانية",
        "Sterile gloves": "قفازات معقمة",
        "Towels prepared": "تجهيز المناشف",
        "Resuscitation area prepared": "تجهيز منطقة الإنعاش",
        "Ambu bag checked": "فحص حقيبة الإنعاش",
        "Drying started within 5s": "بدء التجفيف خلال 5 ثواني",
        "Skin-to-skin contact": "تلامس الجلد للجلد",
        "Baby covered with dry towel/hat": "تغطية الطفل بمنشفة/قبعة جافة",
        "Hygienic cord check": "فحص الحبل السري بنظافة",
        "Delayed cord clamping": "تأخير قطع الحبل السري",
        "Correct cord clamping": "قطع الحبل السري بصورة صحيحة",
        "Early breastfeeding advice": "النصح المبكر بالرضاعة",
        "Head positioned correctly": "وضعية الرأس صحيحة",
        "Correct mask placement": "وضع القناع بصورة صحيحة",
        "Chest rise checked": "التحقق من ارتفاع الصدر",
        "Ventilation rate 30-50/min": "معدل التنفس 30-50/دقيقة",


        // --- IMNCI Training Skill Groups ---
        "Number of training sessions on use of IMNCI tools": "عدد جلسات التدريب على أدوات العلاج المتكامل",
        "Number of training sessions on Main IMNCI Signs Assessment": "عدد جلسات التدريب على تقييم العلامات الأساسية",
        "Number of training sessions on Malnutrition signs Assessment": "عدد جلسات التدريب على تقييم علامات سوء التغذية",
        "Chartbooklet use training sessions": "جلسات التدريب على استخدام كتيب اللوحات",
        "Mother Counseling Card use training sessions": "جلسات التدريب على استخدام كرت نصح الأم",
        "Recording Form filling training sessions": "جلسات التدريب على ملء استمارة التسجيل",
        "Daily and Monthly Statistic Reports filling training sessions": "جلسات التدريب على التقارير الإحصائية",
        "Danger Signs assessment training sessions": "جلسات التدريب على تقييم علامات الخطورة",
        "Respiratory Rate measurement training sessions": "جلسات التدريب على قياس معدل التنفس",
        "Dehydration assessment training sessions": "جلسات التدريب على تقييم الجفاف",
        "Immunization check training sessions": "جلسات التدريب على فحص التطعيم",
        "Weight measurement training sessions": "جلسات التدريب على قياس الوزن",
        "Height measurement training sessions": "جلسات التدريب على قياس الطول",
        "MUAC measurement training sessions": "جلسات التدريب على قياس محيط منتصف الذراع (MUAC)",
        "Z-Score measurement training sessions": "جلسات التدريب على قياس Z-Score",
        "Lower Limb Edema check training sessions": "جلسات التدريب على فحص تورم الأطراف السفلية",

        // --- EENC specific Skills Labels ---
        "Hand Washing": "غسل اليدين",
        "Equipment Preparation": "تجهيز المعدات",
        "Drying": "التجفيف",
        "Skin-to-Skin Contact": "تلامس الجلد للجلد",
        "Suctioning": "الشفط",
        "Cord Pulse Check": "فحص نبض الحبل السري",
        "Clamp Placement": "وضع المشبك",
        "Baby Transfer": "نقل الطفل",
        "Opening Airway": "فتح مجرى الهواء",
        "Ambu Bag Placement": "وضع حقيبة الإنعاش",
        "Ambu Bag Use": "استخدام حقيبة الإنعاش",
        "Ventilation Rate": "معدل التنفس",
        "Corrective Steps": "الخطوات التصحيحية",

        // --- Chart Legend Short Titles ---
        "Meds": "الأدوية", "Tx": "العلاج", "Return": "العودة", "ORS": "التروية", "Fluids": "السوائل", "Rules": "القواعد", "Time": "الوقت", "Comm": "التواصل", "Learned": "تم تعلمه",
        "Imm. S2S": "تلامس فوري", "90min S2S": "تلامس 90 دقيقة", "1st Hr": "الساعة الأولى", "Subs": "بدائل", "Bottle": "زجاجة", "Vit K": "فيتامين ك", "Eye": "العين", "Cord Sub": "مادة الحبل", "Oiling": "تزييت", "Bath <6h": "تحميم <6 ساعات", "Polio": "شلل الأطفال", "BCG": "السل", "Weight": "الوزن", "Temp": "الحرارة", "Civil Reg": "تسجيل مدني", "Card": "كرت خروج",
        "Overall": "الالتزام الكلي", "Assessment": "التقييم", "Decision": "القرار", "Treatment": "العلاج", "Danger Signs Score": "درجة الخطورة", "Measurement Skills Average": "متوسط مهارات القياس", "Resp. Rate": "معدل التنفس", "Dehydration": "الجفاف", "Malnutrition Assessment": "تقييم سوء التغذية", "Immunization": "التطعيم", "Vitamin Assessment": "تقييم فيتامين أ", "Coartem (ACT)": "كورتيم", "Return Immediately": "العودة فوراً", "Return Followup": "المتابعة", "Signs": "العلامات", "Classifications": "التصنيفات", "Treatments": "العلاجات", "Preparation": "التحضير", "Breathing Mgmt": "إدارة التنفس", "Hand Wash 1": "غسل يد 1", "Hand Wash 2": "غسل يد 2", "Gloves": "قفازات", "Towels": "مناشف", "Equip Ready": "تجهيز معدات", "Ambu Check": "فحص حقيبة", "Drying < 5s": "تجفيف <5 ثواني", "Towel/Hat": "منشفة/قبعة", "Hygienic Check": "فحص نظافة", "Delayed Clamp": "تأخير القطع", "Correct Clamp": "قطع صحيح", "BF Advice": "نصح الرضاعة", "Head Pos": "وضعية الرأس", "Mask Seal": "إحكام القناع", "Chest Rise": "ارتفاع الصدر", "Rate": "المعدل",

        // --- Mother Interviews ---
        "Total Mother Interviews": "إجمالي مقابلات الأمهات",
        "Mother Knowledge: Treatment": "معرفة الأم: العلاج",
        "Knows Med Details": "تعرف تفاصيل الأدوية",
        "Knows Treatment Details": "تعرف تفاصيل العلاج المزدوج",
        "Knows Return Date": "تعرف تاريخ العودة",
        "Knowledge (Meds) Over Time": "المعرفة (الأدوية) بمرور الوقت",
        "Mother Knowledge: ORS & Fluids": "معرفة الأم: السوائل وأملاح التروية",
        "Knows ORS Prep": "تعرف تحضير أملاح التروية",
        "Knows Home Fluids": "تعرف السوائل المنزلية",
        "Knows 4 Rules": "تعرف القواعد الأربعة",
        "Knowledge (ORS) Over Time": "المعرفة (أملاح التروية) بمرور الوقت",
        "Mother Satisfaction": "رضا الأم",
        "Satisfaction: Time Spent": "الرضا: الوقت المستغرق",
        "Satisfaction: Communication": "الرضا: أسلوب التواصل",
        "Satisfaction: Learned Something": "الرضا: ما تعلمته",
        "Satisfaction Over Time": "الرضا بمرور الوقت",
        "Overall Mother Interview Scores by": "درجات مقابلة الأم حسب",
        "Average Mother Knowledge/Satisfaction by": "متوسط معرفة/رضا الأم حسب",
        "Detailed Mother Interview Performance": "الأداء التفصيلي لمقابلة الأم",
        
        "Mother Interview: Skin-to-Skin Care": "مقابلة الأم: تلامس الجلد للجلد",
        "Uninterrupted 90min S2S": "تلامس للجلد 90 دقيقة دون انقطاع",
        "Skin-to-Skin Over Time": "تلامس الجلد للجلد بمرور الوقت",
        "Mother Interview: Breastfeeding": "مقابلة الأم: الرضاعة الطبيعية",
        "Feeding in 1st Hour": "الرضاعة في الساعة الأولى",
        "Given Substitutes (Yes)": "إعطاء بدائل الحليب (نعم)",
        "Feeding with Bottle (Yes)": "الرضاعة بالزجاجة (نعم)",
        "Breastfeeding Over Time": "الرضاعة الطبيعية بمرور الوقت",
        "Mother Interview: Skin & Cord Care": "مقابلة الأم: العناية بالجلد والحبل السري",
        "Vitamin K Given": "تم إعطاء فيتامين ك",
        "Eye Ointment Given": "تم إعطاء مرهم العين",
        "Cord Substance Applied": "تم وضع مادة على الحبل السري",
        "Care Indicators Over Time": "مؤشرات العناية بمرور الوقت",
        "Mother Interview: Oiling & Bathing": "مقابلة الأم: التزييت والتحميم",
        "Skin Oiling (Yes)": "تزييت الجلد (نعم)",
        "Bathing < 6hrs (Yes)": "تحميم قبل 6 ساعات (نعم)",
        "Hygiene Indicators Over Time": "مؤشرات النظافة بمرور الوقت",
        "Mother Interview: Vaccination": "مقابلة الأم: التطعيم",
        "Polio Vaccine (Zero)": "لقاح شلل الأطفال (الجرعة الصفرية)",
        "BCG Vaccine": "لقاح السل (BCG)",
        "Vaccination Over Time": "التطعيم بمرور الوقت",
        "Mother Interview: Measurements": "مقابلة الأم: القياسات",
        "Weight Measured": "تم قياس الوزن",
        "Temp Measured": "تم قياس الحرارة",
        "Measurements Over Time": "القياسات بمرور الوقت",
        "Mother Interview: Registration": "مقابلة الأم: التسجيل",
        "Civil Registration": "التسجيل المدني",
        "Discharge Card Given": "تم تسليم كرت الخروج",
        "Registration Over Time": "التسجيل بمرور الوقت",
        "Overall Mother Interview Indicators by": "مؤشرات مقابلة الأم حسب",
        "Average Indicator Presence by": "متوسط توفر المؤشرات حسب",

        // --- Mother Survey Detailed Sentences (AR) ---
        "Mother knows medication details (dose, frequency, days)": "تعرف الأم تفاصيل الدواء (الجرعة، التكرار، الأيام)",
        "Mother knows combination treatment details": "تعرف الأم تفاصيل العلاج المزدوج",
        "Mother knows the 4 rules for home diarrhea management": "تعرف الأم القواعد الأربعة لإدارة الإسهال بالمنزل",
        "Mother knows follow-up return date": "تعرف الأم تاريخ العودة للمتابعة",
        "Mother knows how to prepare ORS": "تعرف الأم كيفية تحضير أملاح التروية",
        "Mother knows allowed home fluids": "تعرف الأم السوائل المنزلية المسموح بها",
        "Mother knows correct water quantity for ORS": "تعرف الأم كمية الماء الصحيحة لأملاح التروية",
        "Mother knows ORS amount to give after each stool": "تعرف الأم كمية أملاح التروية بعد كل تبرز",
        "Satisfaction with time spent by health worker": "الرضا عن الوقت المستغرق مع العامل الصحي",
        "Satisfaction with assessment method": "الرضا عن طريقة التقييم",
        "Satisfaction with given treatment": "الرضا عن العلاج المقدم",
        "Satisfaction with communication style": "الرضا عن أسلوب التواصل",
        "Satisfaction with what was learned": "الرضا عما تم تعلمه",
        "Satisfaction with drug availability at facility": "الرضا عن توفر الأدوية بالمؤسسة",
        "Baby placed skin-to-skin immediately after birth?": "هل تم وضع الطفل تلامس الجلد للجلد فوراً بعد الولادة؟",
        "Baby kept skin-to-skin continuously for 90 minutes?": "هل استمر تلامس الجلد للجلد 90 دقيقة دون انقطاع؟",
        "Baby completed a full feed within first hour?": "هل أكمل الطفل رضعة كاملة خلال الساعة الأولى؟",
        "Baby given any fluids other than breastmilk?": "هل أُعطي الطفل سوائل غير حليب الأم؟",
        "Baby given any fluids via bottle?": "هل أُعطي الطفل أي سوائل بالزجاجة (البزازة)؟",
        "Baby given Vitamin K?": "هل أُعطي الطفل فيتامين ك؟",
        "Baby given Tetracycline eye ointment?": "هل أُعطي الطفل مرهم العين (تتراسيكلين)؟",
        "Anything applied to the cord?": "هل تم وضع أي مادة على الحبل السري؟",
        "Baby rubbed with oil?": "هل تم تزييت جسم الطفل؟",
        "Baby bathed?": "هل تم تحميم الطفل؟",
        "Baby given zero-dose Polio vaccine?": "هل أُعطي الطفل الجرعة الصفرية لشلل الأطفال؟",
        "Baby given BCG vaccine?": "هل أُعطي الطفل لقاح السل (BCG)؟",
        "Baby weighed?": "هل تم وزن الطفل؟",
        "Baby temperature measured?": "هل تم قياس حرارة الطفل؟",
        "Baby registered in civil registry?": "هل تم تسجيل الطفل في السجل المدني؟",
        "Baby given discharge card?": "هل أُعطي الطفل كرت الخروج؟",

        // --- Visit Reports ---
        "Total Visit Reports": "إجمالي تقارير الزيارات",
        "Total Number of Training Sessions": "إجمالي عدد جلسات التدريب",
        "mean sessions per visit": "متوسط الجلسات لكل زيارة",
        "Note: To view Information System and Drug Shortage data, ensure rawReports is included.": "ملاحظة: لعرض إحصائيات نظام المعلومات وانقطاع الأدوية، يرجى التأكد من توفر البيانات الأولية (rawReports).",
        "Information System KPIs (Overall)": "مؤشرات نظام المعلومات (الكلية)",
        "Children seen by IMNCI trained cadre": "أطفال فُحصوا بواسطة كادر مدرب",
        "Children with IMNCI recording form": "أطفال لديهم استمارة تسجيل",
        "Children returning for follow up": "أطفال عادوا للمتابعة",
        "total": "المجموع",
        "trained": "مدرب",
        "Visit": "الزيارة",
        "Seen by Trained Cadre (%)": "فُحص بكادر مدرب (%)",
        "With Recording Form (%)": "باستمارة تسجيل (%)",
        "Return for Follow-up (%)": "عاد للمتابعة (%)",
        "Information System Performance Over Time": "أداء نظام المعلومات بمرور الوقت",
        "KPI Performance (%)": "أداء المؤشر (%)",
        "Facility Drug Availability (Percentage of facilities reporting drugs always available)": "توفر الأدوية بالمؤسسة (نسبة المؤسسات التي تبلغ عن توفر الأدوية دائماً)",
        "Amoxicillin": "أموكسيسيلين",
        "Zinc": "زنك",
        "Availability": "توفر",
        "of": "من",
        "facilities": "مؤسسات",
        "Drug Availability Over Time": "توفر الأدوية بمرور الوقت",
        "Facilities with Drug Available (%)": "مؤسسات يتوفر بها الدواء (%)",
        "Times Trained": "مرات التدريب",
        "% of Total Training Sessions": "% من إجمالي الجلسات",
        "No training data recorded.": "لا توجد بيانات تدريب مسجلة.",
        "Visit Breakdown & Skills Trained by Facility": "تفصيل الزيارات والمهارات المدربة حسب المؤسسة",
        "Facility": "المؤسسة",
        "No visits found for current filter.": "لا توجد زيارات للتصفية الحالية.",
        "Total Visits by": "إجمالي الزيارات حسب",
        "Facility Problems & Solutions (Combined)": "مشاكل المؤسسات والحلول",
        "Problem / Challenge": "المشكلة / التحدي",
        "Implemented Solution": "الحل المتبع",
        "Status": "الحالة",
        "Responsible Person": "المسؤول",
        "No problems recorded.": "لا توجد مشاكل مسجلة."
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    const t = (key) => {
        return translations[language]?.[key] || key; 
    };

    const toggleLanguage = () => {
        setLanguage((prevLang) => (prevLang === 'en' ? 'ar' : 'en'));
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => useContext(LanguageContext);